# Generated by Django 5.2.7 on 2025-12-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
