# Generated by Django 6.0.2 on 2026-03-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('material', 'Material'), ('product', 'Product')], default='material', max_length=100),
        ),
    ]
