# Generated by Django 6.0.2 on 2026-02-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_default_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
