# Generated by Django 6.0.2 on 2026-03-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_materialpreset_materialpresetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('pcs', 'Pieces'), ('liters', 'Liters'), ('grams', 'Grams')], default='pcs', max_length=100),
        ),
    ]
