# Generated by Django 6.0.2 on 2026-03-05 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='materialpreset',
            table=None,
        ),
        migrations.AlterModelTable(
            name='materialpresetitem',
            table=None,
        ),
    ]
