# Generated by Django 6.0.2 on 2026-03-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
