# Generated by Django 5.2.7 on 2026-01-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='line_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
