# Generated by Django 5.2.7 on 2026-01-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_purchase_line_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
