# Generated by Django 5.2.7 on 2025-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_purchase_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
