# Generated by Django 5.2.7 on 2025-11-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0003_purchaseitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
