# Generated by Django 5.2.7 on 2026-02-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0004_preset_presetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
