# Generated by Django 5.2.7 on 2025-12-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_failed_attempts_user_locked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('owner', 'Owner'), ('staff', 'Staff')], max_length=100, null=True),
        ),
    ]
