# Generated by Django 6.0.2 on 2026-02-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_saleitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unsold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
