# Generated by Django 6.0.2 on 2026-03-05 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
        ('Sales', '0003_saleitem_unsold_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_employees', to='Expense.employee')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_employees', to='Sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
