# Generated by Django 6.0.2 on 2026-03-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_saleemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_salary_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
