# Generated by Django 6.0.2 on 2026-03-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_sale_total_salary_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
